### ISSUE TITLE
Fluffy doesn't calculate correctly

### ISSUE THREAD

**Issue by greenDarkness** [jake-white/VGC-2016-Damage-Calculator#20] opened 2017-02-05 02:35 UTC
The Ability Fluffy on Bewear does not give it a fire weakness.

**Comment by Michpem** [comment] 2017-02-07 02:26
Are you calcing Flare Blitz or similar contact moves? Because the fire weakness + the reduced contact damage negate each other (so it deals neutral damage).

**Comment by jake-white** [comment] 2017-02-07 02:33
I do believe that was the case. Flare blitz is 1x effective, non-contact Fire moves are 2x. Working as intended, closing.

**Closed as completed by jake-white** 2017-02-07 02:33 UTC
