### ISSUE TITLE
Z Crystals and Signature Z moves

### ISSUE THREAD

**Issue by cantsay** [jake-white/VGC-2016-Damage-Calculator#35] opened 2017-11-10 13:20 UTC
Z Crystals aren't options as items which affects Knock Off calcs (currently you need to choose a random item). 

If you want to calc a signature Z move (Sparkling Aria > Oceanic Operetta / Thunderbolt > Stoked Sparksurfer etc.) you need to choose the Z move from the moves dropdown. On the Showdown Calc, if you have the correct Z Crystal on the set and click the Z move trigger, instead of getting the generic Z move (Hydro Vortex on Sparkling Aria, Gigavolt Havoc on Thunderbolt), you get the signature Z move instead.

**Comment by jake-white** [comment] 2018-02-08 21:23
This is a duplicate of #28, closing

**Closed as completed by jake-white** 2018-02-08 21:23 UTC
